const cities = {
    "Kibbutz Hagoshrim": "Kibbutz Hagoshrim",
    "Kibbutz Kfar Blum": "Kibbutz Kfar Blum",
    Tveria: "Tveria",
    "Marom Golan": "Marom Golan",
    Evron: "Evron",
    "Maalot Tarshiha": "Maalot Tarshiha",
    Akko: "Akko",
    Nahariya: "Nahariya",
    Haifa: "Haifa",
    "Beit Ashita": "Beit Ashita",
    "Tel-Aviv": "Tel-Aviv",
    "Kibutz Shfayim": "Kibutz Shfayim",
    "Rishon Lezion": "Rishon Lezion",
    "Kfar Adumim": "Kfar Adumim",
    "Bear Tuvia": "Bear Tuvia",
    Beeri: "Beeri",
    Eilat: "Eilat",
    Ashdod: "Ashdod",
    "Ben Shemen": "Ben Shemen",
    Jerusalem: "Jerusalem",
    Modiin: "Modiin",
    Rehovot: "Rehovot",
    Ashdod: "Ashdod",
    "Rishon Letzion": "Rishon Letzion",
    "Rosh Pina": "Rosh Pina",
};
